### ISSUE TITLE
Add security page

### ISSUE THREAD

**Issue by arne-vandamme** [ForeachOS/ax-docs-entity-module#11]
Add separate page explaining how to secure entity views and entity configuration.

Explain concept of `AllowableAction` on entity configuration:
* what is it
* how the different actions are used for the default views
* how to add actions for an entity configuration & single entity

Make sure you don't inadvertently tie in the documentation with ACL module based on the examples. ACL can be mentioned and used in an example (with specification) but it should be clear that `AllowableAction` is the abstract concept and any type of permission checking can be used.

A simple example using basic authority on principal is probably also useful.

**Comment by arne-vandamme** [comment]
When done, add #12 in develop.

**Comment by sgentens** [comment]
available on https://across-docs.foreach.be/across-site/preview/entity-module/3.1.0/securing-entities.html

**Comment by sgentens** [comment]
refactored to https://across-docs.foreach.be/across-site/preview/entity-module/3.1.0/building-views/security-and-permissions.html
