### ISSUE TITLE
EntityModule quick start

### ISSUE THREAD

**Issue by arne-vandamme** [ForeachOS/ax-docs-entity-module#24]
Adaptation of:

- https://www.foreach.be/blog/a-crud-interface-for-your-spring-data-repository-using-across
- https://www.foreach.be/blog/customizing-your-crud-interface-using-across

Must be shortened however.
Start from the Initializr project containing the blog entities. 

Steps to add to the quick start:

- add property to entity with some validator, see it gets added
- customize list & form view
- create simple rich text control (or rendering) to render the blog post body with tinymce

**Comment by sgentens** [comment]
Available on https://across-docs.foreach.be/across-site/preview/entity-module/3.2.0/quick-start.html
